import { clamp } from './coords.js';

function photoPoint(roomId, id, text, sub, u, v, halfU = 0.045, halfV = 0.055) {
  const vTop = clamp(v - halfV, 0, 1);
  const vBottom = clamp(v + halfV, 0, 1);
  return {
    id,
    roomId,
    text,
    sub,
    left: clamp(u - halfU, 0, 1),
    right: clamp(u + halfU, 0, 1),
    top: 1 - vTop,
    bottom: 1 - vBottom,
  };
}

const ROOMS = [
  {
    id: 'operating',
    buildingId: 'sample-care',
    roomName: 'Operating room',
    summary: 'A photographed operating room with the table, the surgical light, the anesthesia machine, and the monitors.',
    credit: 'Photograph by Oliksiy Yakovlyev, CC0 via Poly Haven.',
    imageFile: '/photos/surgery.jpg',
    poster: '/photos/surgery-card.jpg',
    hotspots: [
      photoPoint(
        'sample-operating',
        'or-table',
        'Operating table',
        'The table in the center of the room. The care team helps you onto it and explains what will happen before anything starts.',
        0.5,
        0.62,
        0.07,
        0.06,
      ),
      photoPoint(
        'sample-operating',
        'or-light',
        'Surgical light',
        'The large light above the table. It is bright so the team can see clearly. It may move, and it should not shine straight into your eyes for long.',
        0.5,
        0.32,
        0.06,
        0.07,
      ),
      photoPoint(
        'sample-operating',
        'or-anesthesia',
        'Anesthesia machine',
        'The machine and screens to the left of the table. The anesthesia clinician uses them to watch breathing and comfort, and stays with you.',
        0.3,
        0.52,
      ),
      photoPoint(
        'sample-operating',
        'or-monitors',
        'Monitors',
        'The screens to the right of the table. The team watches the procedure and the patient on them.',
        0.72,
        0.48,
      ),
    ],
  },
  {
    id: 'treatment',
    buildingId: 'sample-care',
    roomName: 'Treatment room',
    summary: 'A photographed hospital room with a bed, a headwall panel, a window, and a chair.',
    credit: 'Photograph by Oliksiy Yakovlyev, CC0 via Poly Haven.',
    imageFile: '/photos/hospital-room.jpg',
    poster: '/photos/hospital-room-card.jpg',
    hotspots: [
      photoPoint(
        'sample-treatment',
        'tx-bed',
        'Hospital bed',
        'The bed in the middle of the room, with white linens and pillows.',
        0.5,
        0.62,
        0.08,
        0.07,
      ),
      photoPoint(
        'sample-treatment',
        'tx-headwall',
        'Headwall',
        'The panel on the wall behind the bed. It holds the outlets and fittings for the equipment beside the bed.',
        0.5,
        0.38,
        0.06,
        0.06,
      ),
      photoPoint(
        'sample-treatment',
        'tx-window',
        'Window',
        'The window with blinds on the right wall. It is where the daylight comes in.',
        0.86,
        0.4,
        0.06,
        0.07,
      ),
      photoPoint(
        'sample-treatment',
        'tx-chair',
        'Visitor chair',
        'A chair in the corner by the window, for someone staying in the room.',
        0.9,
        0.66,
      ),
    ],
  },
  {
    id: 'patient',
    buildingId: 'sample-care',
    roomName: 'Patient room',
    summary: 'A photographed children’s ward with beds, colorful wall panels, windows, and chairs.',
    credit: 'Photograph by Oliksiy Yakovlyev, CC0 via Poly Haven.',
    imageFile: '/photos/childrens-ward.jpg',
    poster: '/photos/childrens-ward-card.jpg',
    hotspots: [
      photoPoint(
        'sample-patient',
        'pt-bed',
        'Hospital bed',
        'A bed in the middle of the ward. Side rails can be up while you rest, and a nurse can show you how to call for help.',
        0.5,
        0.62,
        0.08,
        0.07,
      ),
      photoPoint(
        'sample-patient',
        'pt-window',
        'Window',
        'The windows along the right wall. Curtains can be closed when you want the ward dimmer.',
        0.88,
        0.42,
        0.07,
        0.08,
      ),
      photoPoint(
        'sample-patient',
        'pt-chair',
        'Chair',
        'A chair along the windows, at the edge of the row of beds.',
        0.88,
        0.74,
      ),
      photoPoint(
        'sample-patient',
        'pt-panels',
        'Wall panels',
        'Colorful panels on the left wall, in sight of the beds.',
        0.12,
        0.38,
        0.05,
        0.07,
      ),
    ],
  },
  {
    id: 'office',
    buildingId: 'sample-places',
    roomName: 'Office',
    summary: 'A photographed office with desks, chairs, windows, and ceiling lights.',
    credit: 'Photograph by Sergej Majboroda, CC0 via Poly Haven.',
    imageFile: '/photos/office.jpg',
    poster: '/photos/office-card.jpg',
    hotspots: [
      photoPoint(
        'sample-office',
        'of-desks',
        'Desks',
        'Work surfaces in the middle of the room. A walkthrough can point out where someone would sit for a meeting or a shift.',
        0.52,
        0.62,
        0.07,
        0.06,
      ),
      photoPoint(
        'sample-office',
        'of-windows',
        'Windows',
        'Daylight along the left wall. Curtains or blinds would be the first thing to mention if the room is used for a presentation.',
        0.38,
        0.42,
        0.06,
        0.07,
      ),
      photoPoint(
        'sample-office',
        'of-lights',
        'Ceiling lights',
        'The fixtures overhead. They are part of the room orientation, the same way a surgical light is labeled in a care room.',
        0.58,
        0.33,
        0.05,
        0.05,
      ),
      photoPoint(
        'sample-office',
        'of-chairs',
        'Chairs',
        'Seats pulled up to the desks. A visitor can see where to sit before they walk in.',
        0.46,
        0.7,
      ),
    ],
  },
  {
    id: 'market',
    buildingId: 'sample-places',
    roomName: 'Market hall',
    summary: 'A photographed market hall with stalls, an arched roof, and a walkway.',
    credit: 'Photograph by Andreas Mischok, CC0 via Poly Haven.',
    imageFile: '/photos/market.jpg',
    poster: '/photos/market-card.jpg',
    hotspots: [
      photoPoint(
        'sample-market',
        'mk-walk',
        'Walkway',
        'The open path through the hall. It is the route a visitor would follow between the stalls.',
        0.5,
        0.7,
        0.06,
        0.05,
      ),
      photoPoint(
        'sample-market',
        'mk-stall',
        'Market stall',
        'A stall along the left side of the hall. Labels like this can name a counter, a display, or a checkout.',
        0.38,
        0.55,
        0.06,
        0.07,
      ),
      photoPoint(
        'sample-market',
        'mk-roof',
        'Arched roof',
        'The iron and glass roof overhead. It is a useful landmark when you are describing the building.',
        0.5,
        0.34,
        0.07,
        0.06,
      ),
      photoPoint(
        'sample-market',
        'mk-stall-right',
        'Stall fronts',
        'Shop fronts along the right side. Each one can carry its own point of interest.',
        0.64,
        0.52,
      ),
    ],
  },
  {
    id: 'lakeside',
    buildingId: 'sample-places',
    roomName: 'Lakeside',
    summary: 'A photographed lakeshore with water, trees, and open sky.',
    credit: 'Photograph by Greg Zaal, CC0 via Poly Haven.',
    imageFile: '/photos/lakeside.jpg',
    poster: '/photos/lakeside-card.jpg',
    hotspots: [
      photoPoint(
        'sample-lakeside',
        'lk-water',
        'Lake',
        'The water in front of the camera. Outdoor tours can label a view the same way an indoor tour labels a bed or a table.',
        0.5,
        0.58,
        0.08,
        0.06,
      ),
      photoPoint(
        'sample-lakeside',
        'lk-trees',
        'Trees',
        'Trees along the left shore. They mark the edge of the open water.',
        0.34,
        0.48,
        0.06,
        0.07,
      ),
      photoPoint(
        'sample-lakeside',
        'lk-sky',
        'Sky',
        'Open sky above the lake. Looking up is part of the same 360° photograph.',
        0.55,
        0.28,
        0.06,
        0.05,
      ),
      photoPoint(
        'sample-lakeside',
        'lk-shore',
        'Shore',
        'The near bank underfoot. A label here tells a visitor where the path meets the water.',
        0.48,
        0.74,
      ),
    ],
  },
];

export function sceneById() {
  return null;
}

export function sampleCatalog() {
  return {
    buildings: [
      {
        id: 'sample-care',
        name: 'Care rooms',
        sample: true,
      },
      {
        id: 'sample-places',
        name: 'More places to try',
        sample: true,
      },
    ],
    rooms: ROOMS.map((room) => ({
      id: `sample-${room.id}`,
      buildingId: room.buildingId,
      name: room.roomName,
      summary: room.summary,
      credit: room.credit,
      imageFile: room.imageFile,
      poster: room.poster,
      scene: '',
      sample: true,
    })),
    hitboxes: ROOMS.flatMap((room) => room.hotspots),
  };
}
